version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.0
      - image: circleci/node:8.11.1
    steps:
      - checkout
      - run:
          name: pre
          command: sh ./bin/setup
  test:
    docker:
      - image: circleci/ruby:2.5.0
      - image: circleci/node:8.11.1
    steps:
      - checkout
      - run:
          name: build
          command: bundle exec jekyll build
      - run:
          name: htmlproofer
          command: bundle exec htmlproofer ./_site --only-4xx --allow-hash-href

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            branches:
              only: master